server:
  port: 8080

eureka:  
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courses-service
          uri: lb://courses-service
          predicates:
            - Path=/courses/**
