server:
  port: 8080

eureka:  
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://root:YxqnDcmtxMrpYVuPNojRkVKrfBkftAMT@viaduct.proxy.rlwy.net:15921/railway
    username: root
    password: YxqnDcmtxMrpYVuPNojRkVKrfBkftAMT
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courses-service
          uri: lb://courses-service
          predicates:
            - Path=/api/v1/courses/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/api/v1/posts/**
        - id: articles-service
          uri: lb://articles-service
          predicates:
            - Path=/api/v1/articles/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
